services:
  web-api:
    image: ${DOCKER_REGISTRY-}web-api
    container_name: web-api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=SharpBuy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80

  smtp4dev:
    image: rnwood/smtp4dev:v3
    container_name: smtp4dev
    restart: always
    ports:
      - "5002:80"   # Interfejs webowy
      - "2525:25"   # Port SMTP
    volumes:
      - ./.containers/smtp4dev-data:/var/lib/smtp4dev/data
    environment:
      - ServerOptions__HostName=smtp4dev
